syntax = "proto2";

package RobotCommandProtobuf;

option java_package = "tw.edu.cgu.ai";

import "google/protobuf/timestamp.proto";

//The command that the server sends to the robot
message RobotCommand {
  optional string speak_sentence = 1;
  optional int32 turnspeed = 9;
  optional int32 yaw = 2;
  optional int32 pitch = 3;
  optional int32 headspeed = 4;
  optional int32 face = 5;
  optional bool hideface = 6;
  optional int32 dancetype = 10;

  enum FaceEnum{
    TTS_AngerA = 0;
    TTS_AngerB = 1;
    TTS_Contempt = 2;
    TTS_Disgust = 3;
    TTS_Fear = 4;
    TTS_JoyA = 5;
    TTS_JoyB = 6;
    TTS_JoyC = 7;
    TTS_PeaceA = 8;
    TTS_PeaceB = 9;
    TTS_PeaceC = 10;
    TTS_SadnessA = 11;
    TTS_SadnessB = 12;
    TTS_Surprise = 13;
    }

  optional int32 stopmove = 7;
  optional int32 motion = 8;
  optional string content = 11;
  optional bool killapp = 12;
  optional string sface = 13;
  optional string smotion = 14;
}

//The message that the robot sends to the server
message RobotToServerMessage {
  optional google.protobuf.Timestamp event_time = 1;
  optional int32 jpegdatalength = 2;
  optional bytes jpegdata = 3;
  optional string description = 4;
  optional int32 numberpressed = 5;
  optional float yaw = 6;           //why I cannot use float in my message?
  optional float pitch = 7;
  optional string tabletcommand = 8;
}

