// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        agp_version = '9.3.1'
        kotlin_version = '1.8.22' // Set your desired Kotlin version here
    }
    repositories {
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        google()
        gradlePluginPortal()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$agp_version"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath 'com.google.protobuf:protobuf-gradle-plugin:0.9.4'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.2.10'
        classpath 'org.jetbrains.kotlin:compose-compiler-gradle-plugin:2.2.10'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
